FROM centos:6

RUN set -x \
    && yum install epel-release -y

RUN yum install -y make gcc gcc-c++ git python openssl-devel rpm-build cmake28 sudo wget R

# create jenkins user, make sudo. try to keep this toward the bottom for less cache busting
ARG JENKINS_GID=999
ARG JENKINS_UID=999
RUN groupadd -g $JENKINS_GID jenkins && \
    useradd -m -d /var/lib/jenkins -u $JENKINS_UID -g jenkins jenkins && \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
